projects:
  Cars App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: rj7uic2fmjfrpbothvoyi4wyqm
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        maxDepth: 2
      endpoints:
        prod: >-
          https://vdzchgxfvbddjk5p4xsyp3g6o4.appsync-api.us-east-1.amazonaws.com/graphql
